name: Generate Diagrams

on: [push]

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PlantUML
      run: sudo apt-get install -y plantuml
    - name: Generate Diagrams
      run: plantuml -tpng **/*.puml
    - name: Upload Diagrams
      uses: actions/upload-artifact@v2
      with:
        name: Diagrams
        path: ./**/*.png
